client/components/navbar.js
package.json

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_

oauth is working

---

client/components/index.js
client/components/stock-card.js
client/routes.js
package-lock.json
package.json
public/index.html

Semantic script and installation completion

Stock card and semantic

---

client/components/stock-card.js
package-lock.json

First draft of Stock Card Component complete
#3

Stock card

---

client/components/auth-form.js
client/components/navbar.js
package-lock.json

navbar 1st draft

---

client/components/index.js
client/components/landing-page.js
client/routes.js
package-lock.json
package.json

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_

Main victory graph

---

client/components/stock-card.js
client/sass/index.scss
package-lock.json
package.json
webpack.config.js

Basic Bulma set-up:
Sass file added to client
Index in Sass
Webpack config set-up
Dependencies in package.json

Basic Bulma set-up

---

client/components/navbar.js

Navbar bulma

---

client/components/navbar.js

Navbar functionality in place up until admin

functionality up to admin

---

public/index.html

Reset master without semantic and Michael's override

Reset master branch without semantic

---

client/components/landing-page.js
client/components/orders.js
client/components/single-indice.js
client/routes.js

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_

up to date with master

---

client/routes.js

Quick Bug Fix

---

client/app.js
client/components/all-memes.js
client/components/footer.js
client/components/homepage.js
client/components/trending-memes.js

Just some simple consistency fixes (changed from global is-medium to is-small) and some spelling/titling

Quick fixes

---

public/style.css

Bracket added

---

client/components/homepage.js
client/sass/abstracts/variables.scss
public/style.css

Color scheme and font with deleted home

---

client/app.js
client/components/homepage.js
client/components/navbar.js
client/sass/abstracts/variables.scss
public/style.css

Basic layout for homepage and transparent nav

Homepage makeover

---

client/components/homepage-card-button.js
client/components/homepage.js
client/routes.js
client/sass/abstracts/variables.scss

Button cards add to homepage
-Clickable...right now the last card is directed to /indices but as of yet I don't have that component, so the link is working, but its just directing to the homepage.
-I may add background frames for color (border) but I haven't decided yet

Button cards added

---

client/components/single-meme-renders/meme-orders.js
server/api/offers.js

fixed bugs in creating offers, and matching buy offers.

fixed bugs in creating offers

---

client/components/stock-card-small.js
public/style.css

colors change based on percent being negative or positive

---

client/components/navbar.js
client/sass/abstracts/variables.scss

Navbar spaced correctly and link for logged in user

---

client/components/stock-card-small.js
client/sass/abstracts/variables.scss

file error clean up

---

client/components/auth-form.js
client/components/homepage-card-button.js
client/components/index.js
client/components/navbar.js
client/components/stock-card-small.js
client/sass/abstracts/variables.scss

Box coloring fixed and typo changed

---

client/components/homepage.js

Homepage changes

---

client/components/homepage.js
client/components/navbar.js
client/sass/abstracts/variables.scss

Spacing changes to homepage

---

client/components/footer.js
client/components/homepage.js
client/components/navbar.js
client/components/ticker-tape.js
client/sass/abstracts/variables.scss

Homepage button changes and footer

---

client/components/all-memes.js
client/components/homepage-card-button.js
client/components/stock-card-small.js
client/sass/abstracts/variables.scss

Css changes

---

client/components/market-chart.js
client/components/portfolio.js

Axis changes

---

client/store/memes.js
server/api/memes.js

Can now buy indices without issue

can now buy indices without issue
